# Generated by Django 5.1.4 on 2025-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('hot', 'Hot Coffee'), ('cold', 'Cold Coffee')], max_length=4)),
                ('image', models.ImageField(upload_to='menu_images/')),
            ],
        ),
    ]
